language: php

dist: trusty

php:
  - '7.1'
  - '7.2'

before_install:
  - composer self-update

install:
  - composer install

script:
  - php "./vendor/codeception/codeception/codecept" run --steps --coverage

notifications:
  irc: "irc.freenode.org#ltb-project"
