# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See http://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /
    defaults:
        _controller: App\Controller\DefaultController::indexAction

change-password:
    path: /change-password
    defaults:
        _controller: App\Controller\ChangePasswordController::indexAction

change-security-question:
    path: /change-security-question
    defaults:
        _controller: App\Controller\ChangeSecurityQuestionsController::indexAction

change-ssh-key:
    path: /change-ssh-key
    defaults:
        _controller: App\Controller\ChangeSshKeyController::indexAction

reset-password-by-question:
    path: /reset-password-by-question
    defaults:
        _controller: App\Controller\ResetPasswordByQuestionController::indexAction

reset-password-by-email:
    path: /reset-password-by-email
    defaults:
        _controller: App\Controller\GetTokenByEmailVerificationController::indexAction

reset-password-by-sms:
    path: /reset-password-by-sms
    defaults:
        _controller: App\Controller\GetTokenBySmsVerificationController::indexAction

reset-password-with-token:
    path: /reset-password-with-token
    defaults:
        _controller: App\Controller\ResetPasswordByTokenController::indexAction